@host=http://localhost:5192

POST {{host}}/auth/register
Content-Type: application/json

{
  "firstName": "Elizabeth",
  "lastName": "Salazar",
  "email": "elizabethsalazar@gmail.com",
  "password": "P@ssword1"
}