@host=http://localhost:5192
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ODdkZjk4OC00MTI0LTQ4ZTAtOTk1OC0wY2QyZDUwOTZiYTgiLCJnaXZlbl9uYW1lIjoiRGF2aWQiLCJmYW1pbHlfbmFtZSI6IkJhbnplciIsImp0aSI6IjUxNzI2NzNjLWFjZTAtNGNmNi04NmNkLWU0NzY4M2RiZmQ2MSIsImV4cCI6MTY5NzM0NTM4OCwiaXNzIjoiRmluYW56YXNQZXJzb25hbGVzIiwiYXVkIjoiRmluYW56YXNQZXJzb25hbGVzIn0.PH-qi1wMpFebZTix6mF3fgjymLIS64YQu4HF5yYv3hk
POST {{host}}/movements
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "description" : "Egresando movimiento.. 1",
    "amount" : 10.00,
    "type" : "E",
    "accountId" : "3089b2a8-1795-49e2-be9e-2a5b573e291d",
    "categoryId": "46bd51ad-115d-41d2-ba9c-121797e6b1b7"
}