@host=http://localhost:5192
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NjdkN2Y4MS0zNjVmLTRlN2UtYjliOS03ZjBjZWYzYjI0MGMiLCJnaXZlbl9uYW1lIjoiRGF2aWQiLCJmYW1pbHlfbmFtZSI6IkJhbnplciIsImp0aSI6IjBlNmU1NGE5LTY1NTEtNDgxZi04ZTUwLTYxNjYxMjk3ZmI0YSIsImV4cCI6MTY5OTI4NTUyNiwiaXNzIjoiRmluYW56YXNQZXJzb25hbGVzIiwiYXVkIjoiRmluYW56YXNQZXJzb25hbGVzIn0.9UycBLCSAxVHw67rZR9CIosicfYAZlvkYylGO9GRb3I
POST {{host}}/movements
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "description" : "Primer egreso",
    "amount" : 20.00,
    "type" : "E",
    "accountId" : "34b659e6-c1b8-4a75-a812-8d369fa7ee8a",
    "categoryId": "8ba39f06-5552-4667-8571-c84b8a94abf3",
    "createdDate": "2023-10-19T15:30:00.000Z"
}